## Cargo config file

# Environment variables set for al `cargo ...` commands
[env]
# Scope down tracing, to filter our external lib tracing.
RUST_LOG = "lib_auth=debug,lib_core=debug,lib_rpc=debug,lib_utils=debug,web_server=debug"


## Service Environment Variables 
# NOTE:
#   For cargo commands only.
#   For deployed env, should be managed by container 
#   (e.g., Kubernetes).

## Secrets
# Keys and passwords below are for localhost dev ONLY.
SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"

SERVICE_PWD_KEY = "0pONppasb1kLFhV0sSKbQmAtOFzHQDGjG_dBFU-QUiBbtjydZJtmHQAv4lHg04hwLLl0kFqSwQXjltMpUhFyOQ"
SERVICE_TOKEN_KEY = "DWnh8gjLb0uiU2CcudYqYvDPQkrxbISOI1Ab7PKGt69bO07S0FKyHuMUBw1-rFK8NeOtlCWTs4Vx_EVIgwwzHQ"

## Config Map
SERVICE_TOKEN_DURATION_SEC = "1800" # 30 minutes
# TODO: Switch to absolute path for production.
SERVICE_WEB_FOLDER = "web_folder/"
